"""empty message

Revision ID: 733f4434a007
Revises: fe32ce25cf04
Create Date: 2023-04-15 17:44:16.270281

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '733f4434a007'
down_revision = 'fe32ce25cf04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('question_hitter',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], name=op.f('fk_question_hitter_question_id_question'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_question_hitter_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'question_id', name=op.f('pk_question_hitter'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('question_hitter')
    # ### end Alembic commands ###
